---
layout: post
title: ROS2 tutorial 중 겪은 문제 및 해결
tags: study
---
Created Date: 2020.11.1  
Modified Date: 2020.11.2

# 패키지 빌드 전 rosdep 실행 시 문제

[실습 링크(creating a workspace)](https://index.ros.org/doc/ros2/Tutorials/Workspace/Creating-A-Workspace/)  
**문제 발생**
```shell
~devel_ws$ rosdep install -i --from-path src --rosdistro foxy -y
```
새로 만든 패키지를 빌드하기 위해 위의 rosdep 명령을 실행하던 중 문제가 발생했다.
```shell
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
turtlesim: Unsupported OS [mint]
```
<br>

**문제 해결**  
`--os=ubuntu:mint` 옵션을 추가하여 실행하였더니 원하는 결과가 나왔다.
```shell
~/dev_ws$ rosdep install -i --from-path src --rosdistro foxy -y --os=ubuntu:mint
#All required rosdeps installed successfully
```

- *reference*
  - [https://answers.ros.org/question/40081/rosdep-doesnt-recognize-os/](https://answers.ros.org/question/40081/rosdep-doesnt-recognize-os/)
  - [https://github.com/ros-infrastructure/rosdep/issues/10](https://github.com/ros-infrastructure/rosdep/issues/10)
---
<br>

# 시뮬레이션 해 생성한 map 저장 시 문제  

[실습 링크(1.2.1.4 virtual SLAM with Turtlebot3)](https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_simulation/#ros-2-simulation)  
**문제 발생**  
e-manual에서의 방법 그대로 실행했더니 오류가 발생했다.
```shell
~$ ros2 run nav2_map_server map_saver -f ~/map
No executable found
```
<br>

**문제 해결**  
`map_saver`대신 `map_saver_cli`로 실행하였더니 해결되었다.
```shell
~$ ros2 run nav2_map_server map_saver_cli -f ~/map
```

- *reference*  
  - [https://github.com/ros-planning/navigation2/tree/main/nav2_map_server](https://github.com/ros-planning/navigation2/tree/main/nav2_map_server)
---
<br>

# 저장한 map을 turtlebot3_navigation navigation.launch.py로 불러올 때 문제  

[실습 링크(1.2.1.5 Virtual Navigation with Turtlebot3)](https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_simulation/#ros-2-simulation)  
**문제 발생**  
e-manual대로 실습 중 '2. Execute Navigation'단계의 명령을 실행하다가 오류가 발생했다.  
```
~$ ros2 launch turtlebot3_navigation2 navigation2.launch.py use_sim_time:=True map:=$HOME/map.yaml
[INFO] [launch]: All log files can be found below /home/kodogyu/.ros/log/2020-11-03-12-00-34-585692-kodogyu-virtual-machine-2344
[INFO] [launch]: Default logging verbosity is set to INFO
/home/kodogyu/turtlebot3_ws/install/turtlebot3_navigation2/share/turtlebot3_navigation2/launch/navigation2.launch.py:78: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  Node(
/home/kodogyu/turtlebot3_ws/install/turtlebot3_navigation2/share/turtlebot3_navigation2/launch/navigation2.launch.py:78: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  Node(
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 125, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_description_source.py", line 51, in _get_launch_description
    return get_launch_description_from_python_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 62, in get_launch_description_from_python_launch_file
    launch_file_module = load_python_launch_file_as_module(python_launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 37, in load_python_launch_file_as_module
    loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ros/foxy/share/nav2_bringup/launch/nav2_bringup_launch.py'
```
<br>
